# Generated by Django 3.0.8 on 2020-07-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_auto_20200716_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='fruit_image',
        ),
    ]
